
synced_folder: ~/Sites/nbcu

memory: 2048
cpus: 2

sites:
- subscription: nbcupublisher7
  shortname: nbcupublisher7 
  vhost:
    servername: local.publisher7.com
    documentroot: Publisher7/docroot
- subscription: nbcunbc
  shortname: nbcunbc
  vhost:
    servername: local.nbc.com
    documentroot: Publisher7_nbc/docroot
- subscription: nbcutelemundo
  shortname: nbcutelemundo
  vhost:
    servername: local.telemundo.com
    documentroot: Publisher7_nbcutelemundo/docroot
- subscription: patternlabnbcutelemundo
  shortname: patternlabtlmd
  vhost:
    servername: patternlab.local.telemundo.com
    documentroot: Publisher7_nbcutelemundo/prototype/patternlab-php/public
- subscription: nbcuuomerch
  shortname: nbcuuomerch
  vhost:
    servername: local.nbcuuomerch.com
    documentroot: Publisher7_nbcuuomerch/docroot
