---
# Set to the local folder you want shared to the VM.
synced_folder: "~/Sites/www"

# Adjust the Base Memory provisioned for the VM.
memory: "1024"

# Define a list of sites with the following keys:
# shortname       = site's shortname
# vhost           = assoc array with:
#   servername    = domain name
#   documentroot  = site docroot, relative to synced_folder
#
# Example:
#  sites:
#  - shortname: "site1"
#    vhost:
#      servername: "local.site1.com"
#      documentroot: "site1/docroot"
#  - shortname: "site2"
#    vhost:
#      servername: "local.site2.com"
#      documentroot: "site2/docroot"
